### ISSUE TITLE
What about using the embedding of Other class?

### ISSUE THREAD

**Issue by vhientran** [onehaitao/CR-CNN-relation-extraction#1]
Hi @onehaitao,

Thank you very much for releasing your source code. I have run your source code, and achieved the good performance (official F1-score: 83.36%). I only wonder that why you use the embedding of _Other_ class in [line](https://github.com/onehaitao/CR-CNN-relation-extraction/blob/9139f0c7e8863aae48e5f75c364949f94e6467c6/model.py#L104) (with num_class=19, instead of num_class=18), while in the [original paper](https://aclanthology.org/P15-1061.pdf), the author did not use the embedding of _Other_ class.

Thank you for your help!

**Comment by onehaitao** [comment]
Thanks for your question. Actually, in order to omit the effect of the embedding of *Other* class, the score of *Other* class is manually set to 0 in [line](https://github.com/onehaitao/CR-CNN-relation-extraction/blob/9139f0c7e8863aae48e5f75c364949f94e6467c6/model.py#L120) . It can be considered as same as that describled in paper.

**Comment by vhientran** [comment]
I got it. Thank you for your quick reply!
